
server:
  port: ${PORT:8334}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: password123
      database: demo-school
      authentication-database: admin